### PR TITLE
Fix deep highlighting clicks while node is selected

### LINKED ISSUE #4: Highlighting does not refresh when clicking the deep highlight button
Description:
When clicking the 'Deep Usage Highlighting' button with a node already selected, the highlighting links will not refresh

Repro steps:
1) Open the site
2) Click on a node
3) Click the 'Deep Usage Highlighting' button

Actual results:
The 'level 2+' highlight links do not appear until reselecting the node

Expected results:
The level 'level 2+' highlighting links appear without needing to click the node again

### PR DESCRIPTION
**Pull request by Cellv2**
Fix #4 

This adds in a force rehighlighting function which triggers when clicking the doDeepUsage input element. It does this by keeping track of the currently selected box and utilising that when clicking the input

I would use boxFocused. however as the current listeners make this undefined when clicking off of the box via bgClick I thought it easier to just keep track of it this way

### CODE REVIEW

**Comment by Cellv2** [comment]
Sorry, just noticed there's no gitignore so .vscode\settings.json crept in

I've updated the PR to remove this

**Comment by kukuminer** [comment]
Hey @Cellv2, thanks for your PR!
I had a look and I noticed that we can actually use `boxFocused` instead of a new `currentBox` variable. We can change line 280 to 
`boxFocused = box` from `.. = box.id`
to accommodate.
Resetting `boxFocused` in the `boxClick` function (line 273) also prevents a specific bug (clicking another box while one is in focus and after clicking the checkbox)

I'll put some comments on your PR to indicate the changes that I think would simplify this PR as I outlined above.

I hope what I said is clear, if you have any questions please don't hesitate to ask!

File: script.js [hunk 1]
```diff
@@ -1,6 +1,8 @@
 var boxFocused = undefined;
+let currentBox = null;
```
Comment (kukuminer) [inline script.js]: We can use `boxFocused` for this purpose, so remove this variable and refactor all uses

File: script.js [hunk 2]
```diff
@@ -145,6 +154,7 @@ function boxHover(event)
 	if(!boxFocused)
 	{
 		highlight(event.target);
+		currentBox = event.target;
```
Comment (kukuminer) [inline script.js]: This isn't necessary since they can't click the checkbox while hovering on a mod box, but we can leave it in for future development (just make sure to refactor)

**Comment by Cellv2** [comment]
@kukuminer Sure thing, honestly I did a quick hack to get it put together, I probably should have read the code more closely 😄 

Will take a look through and update the PR

**Review by kukuminer — CHANGES_REQUESTED** [review]
Don't forget to change line 281: 
`boxFocused = box.id` => `boxFocused = box`

Thanks again for your PR!

**Comment by Cellv2** [comment]
@kukuminer PR updated with requested changes

Also, the bug you mentioned on like 273 is exactly what I hit when trying to originally refactor, but I just didn't look closely enough at what is being passed around to notice the quick change of box.id to box on line 279, thanks for pointing it out

File: script.js (hunk 2 above)
Comment (Cellv2) [reply script.js]: Really isn't needed as you said, but left it in anyway

Comment (kukuminer) [reply script.js]: I was actually wrong about this and didn't realize the implications- this prevents the box from un-highlighting after the cursor leaves it. We'll need to remove this line for it to work as intended, sorry about that

File: script.js [hunk 3]
```diff
@@ -145,6 +153,7 @@ function boxHover(event)
 	if(!boxFocused)
 	{
 		highlight(event.target);
+		boxFocused = event.target;
```
Comment (kukuminer) [inline script.js]: I didn't notice but this actually stops the box from un-highlighting. I think we just remove this line for now and we can add it back in a different way if we need to use this feature later. Sorry for the confusion

**Review by kukuminer — CHANGES_REQUESTED** [review]

**Comment by Cellv2** [comment]
@kukuminer Sorry I shouldn't code when I am so tired. This was something I noticed originally and was another reason I added the second variable (didn't quite look through enough to figure out why). I've removed it

**Review by kukuminer — APPROVED** [review]
Looks good! Did some quick testing and it works. Thanks so much for the PR and for the changes 😄
